
###
### Tester l'inscription d’un utilisateur
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "ouziri",
  "password": "Azerty123!",
  "email": "ouzirir@example.com"
}

###
### Tester la connexion d’un utilisateur
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "ouziri",
  "password": "Azerty123!"
}

###
### Récupérer une map
GET http://localhost:8080/maps/abc123

###
### Création d'une map de test qui se nomme xyz789 avec 88 hitObjects
POST http://localhost:8080/maps?hash=xyz789&hitObjects=88
###

### Créer un score pour l’utilisateur `ouziri` sur la map `xyc789`
POST http://localhost:8080/scores?username=ouziri&hash=xyz789&timestamp=1717855000000

###
### Récupérer tous les scores de `ouziri`
GET http://localhost:8080/scores/user/ouziri

###
### Récupérer tous les scores de la map `abc123`
GET http://localhost:8080/scores/map/abc123

###
### Récupérer tous les scores de la map `xyz789`
GET http://localhost:8080/scores/map/xyz789

###
### Récupérer le highscore de `ouziri` sur la map `xyz789`
GET http://localhost:8080/scores/highscore?username=ouziri&hash=xyz789

###
### Récupérer les infos d’un utilisateur
GET http://localhost:8080/users/ouziri

###
### Déconnexion
POST http://localhost:8080/auth/logout



